// Generated by export_data.py from saved project outputs.
window.OBSERVATORY_DATA = {
  "stats": [
    {
      "class_id": "1",
      "class_name": "Very Low",
      "index_min": "0.0",
      "index_max": "0.1916",
      "area_km2": "425.233",
      "percent_of_study_area": "19.97"
    },
    {
      "class_id": "2",
      "class_name": "Low",
      "index_min": "0.1916",
      "index_max": "0.2226",
      "area_km2": "486.029",
      "percent_of_study_area": "22.82"
    },
    {
      "class_id": "3",
      "class_name": "Moderate",
      "index_min": "0.2226",
      "index_max": "0.2461",
      "area_km2": "332.503",
      "percent_of_study_area": "15.61"
    },
    {
      "class_id": "4",
      "class_name": "High",
      "index_min": "0.2461",
      "index_max": "0.2929",
      "area_km2": "454.624",
      "percent_of_study_area": "21.35"
    },
    {
      "class_id": "5",
      "class_name": "Very High",
      "index_min": "0.2929",
      "index_max": "1.0",
      "area_km2": "431.413",
      "percent_of_study_area": "20.26"
    }
  ],
  "weights": [
    {
      "criterion": "flood",
      "target_AHP": "0.35",
      "AHP": "0.346029",
      "Entropy": "0.76259",
      "AHP+Entropy (used)": "0.55431",
      "CRITIC": "0.162111"
    },
    {
      "criterion": "landslide",
      "target_AHP": "0.3",
      "AHP": "0.304569",
      "Entropy": "0.006239",
      "AHP+Entropy (used)": "0.155404",
      "CRITIC": "0.172612"
    },
    {
      "criterion": "exposure",
      "target_AHP": "0.2",
      "AHP": "0.199277",
      "Entropy": "0.056377",
      "AHP+Entropy (used)": "0.127827",
      "CRITIC": "0.339511"
    },
    {
      "criterion": "fire",
      "target_AHP": "0.15",
      "AHP": "0.150124",
      "Entropy": "0.174794",
      "AHP+Entropy (used)": "0.162459",
      "CRITIC": "0.325767"
    }
  ],
  "validation": {
    "event": "July 2024 Mundakkai-Chooralmala landslide",
    "quantile_breaks": [
      0.43273565022976435,
      0.4801818105833672,
      0.527194895993186,
      0.644276802512355
    ],
    "headline_passed": true,
    "results": [
      {
        "label": "verified",
        "lat": 11.486,
        "lon": 76.156,
        "buffer_m": 2000,
        "point_class": 4,
        "point_class_name": "High",
        "point_index": 0.6424727197806503,
        "zone_mean_index": 0.6208472176617326,
        "zone_class_histogram": {
          "Very Low": 0.0808,
          "Low": 0.0105,
          "Moderate": 0.2276,
          "High": 0.2233,
          "Very High": 0.4578
        },
        "zone_modal_class": "Very High",
        "zone_fraction_high_or_very_high": 0.6811,
        "zone_factor_contributions": {
          "elevation": 0.21986152069849155,
          "ndvi": 0.13548256978067696,
          "rainfall": 0.225,
          "slope": 0.34741063620393386
        },
        "aoi_factor_contributions": {
          "elevation": 0.21071787518689497,
          "ndvi": 0.16852792550157678,
          "rainfall": 0.1801813253738807,
          "slope": 0.23491409091756624
        },
        "passed": true
      },
      {
        "label": "brief",
        "lat": 11.49,
        "lon": 76.23,
        "buffer_m": 2000,
        "outside_study_area": true,
        "passed": false,
        "note": "zone has no valid pixels: the coordinate lies outside the study area"
      }
    ]
  },
  "availability": {
    "routes": false,
    "summary": false,
    "composite_raster": false
  },
  "sources": [
    "outputs/risk_stats.csv",
    "outputs/mcdm_weights.csv",
    "outputs/landslide_validation.json"
  ],
  "scene": "illustrative"
};
