"""Bundle saved pipeline summaries into a browser script; no GEE/network needed.

Run from any directory: python frontend/export_data.py
The draft intentionally keeps procedural scene geometry separate from real results.
"""
from pathlib import Path
import csv
import json

ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ROOT / "outputs"


def read_csv(name):
    path = OUTPUTS / name
    if not path.exists():
        return []
    with path.open(encoding="utf-8-sig", newline="") as file:
        return list(csv.DictReader(file))


def read_json(name):
    path = OUTPUTS / name
    return json.loads(path.read_text(encoding="utf-8-sig")) if path.exists() else None


def export():
    payload = {
        "stats": read_csv("risk_stats.csv"),
        "weights": read_csv("mcdm_weights.csv"),
        "validation": read_json("landslide_validation.json"),
        "availability": {
            "routes": (OUTPUTS / "routes.geojson").exists(),
            "summary": (OUTPUTS / "summary.json").exists(),
            "composite_raster": (OUTPUTS / "rasters" / "risk.tif").exists(),
        },
        "sources": ["outputs/risk_stats.csv", "outputs/mcdm_weights.csv", "outputs/landslide_validation.json"],
        "scene": "illustrative",
    }
    # Escape script-sensitive characters so the bundle is safe to embed later.
    encoded = json.dumps(payload, ensure_ascii=True, indent=2).replace("<", "\\u003c")
    target = Path(__file__).with_name("data.js")
    target.write_text("// Generated by export_data.py from saved project outputs.\nwindow.OBSERVATORY_DATA = " + encoded + ";\n", encoding="utf-8")
    print(f"Wrote {target}: {len(payload['stats'])} risk classes, {len(payload['weights'])} weights")


if __name__ == "__main__":
    export()
